openapi: 3.0.3
info:
  contact:
    name: "OpenWeatherMap API"
    url: "https://openweathermap.org/api"
    email: "some_email@gmail.com"
  title: Ticket Show Application
  description:
    <h2> Venue Table Schema </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>venueid</td>
            <td>Integer</td>
            <td>Primary Key</td>
          </tr>
          <tr>
            <td>name</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>
          <tr>
            <td>place</td>
            <td>String</td>
            <td></td>
          </tr>      
          <tr>
            <td>capacity</td>
            <td>String</td>
          </tr>         
        </tbody>
      </table>

    <h2> Show Table Schema </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>showid</td>
            <td>Integer</td>
            <td>Primary Key</td>
          </tr>
          <tr>
            <td>showname</td>
            <td>String</td>
            <td>Not Null</td>
          </tr>
          <tr>
            <td>rating</td>
            <td>Integer</td>
            <td></td>
          </tr>
          <tr>
            <td>price</td>
            <td>Integer</td>
          </tr>
          <tr>
            <td>showcapacity</td>
            <td>Integer</td>
          </tr>
          <tr>
            <td>eshowid</td>
            <td>Integer</td>
          </tr>      
          
        </tbody>
      </table>

  version: 1.0.0
  
servers:
  - url: http://127.0.0.1:5000
tags:
  - name: venue
    description: Venue Management
  - name: show
    description: Show Management
paths:
  /api/venues/{venueid1}:
    get:
      tags:
        - venue
      summary: venue of all listnames
      description: venue of all listnames
      parameters:
        - in: path
          name: venueid1
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 2
                  lists:
                    type: array
                    example: [venue_names]
                    
        '404':
          description: User not found
        '500':
          description: Internal Server Error
          
  /api/createvenue/{venueid}:
    post:
      tags:
        - venue
      summary: Create a new venue
      description: Create a new venue
      parameters:
        - in: path
          name: venueid
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: venue_name
                description:
                  type: string
                  example: venue_description
      responses:
        '200':
          description: Venue created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: venue_name
                  description:
                    type: string
                    example: venue_description
                  user_id:
                    type: integer
                    example: 1
                  
        '409':
          description: Venue Name already exists
        '500':
          description: Internal Server Error

  /api/deletevenue/{venueid}:
    delete:
      tags:
       - venue
      summary: Delete the venue
      description: Delete the venue
      parameters:
        - in: path
          name: venueid
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: Venue not found
        '500':
          description: Intenal Server Error
          
  /api/updatevenue/{venueid}:
    put:
      tags:
        - venue
      summary: Update the venue
      description: Update the venue
      parameters:
        - in: path
          name: venueid
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: venue_name
                description:
                  type: string
                  example: venue_description
      responses:
        '200':
          description: Venue updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: venue_name
                  description:
                    type: string
                    example: venue_description
                  user_id:
                    type: integer
                    example: 1
                  
        '404':
          description: Venue Name not exists
        '500':
          description: Internal Server Error
          
  /api/shows/{showid}:
    get:
      tags:
        - show
      summary: venue of all shownames
      description: venue of all shownames
      parameters:
        - in: path
          name: showid
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  list_id:
                    type: integer
                    example: 2
                  cards:
                    type: array
                    example: [show_names]
                    
        '404':
          description: Show not found
        '500':
          description: Internal Server Error
  
  /api/createshow/{showid}:
    post:
      tags:
        - show
      summary: Create a new show
      description: Create a new show
      parameters:
        - in: path
          name: showid
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: show_name
                content:
                  type: string
                  example: show_content
      responses:
        '201':
          description: Show created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: show_name
                  content:
                    type: string
                    example: show_content

        '409':
          description: Show Name already exists
        '500':
          description: Internal Server Error

  /api/deleteshow/{eshowid}:
    delete:
      tags:
       - show
      summary: Delete the show
      description: Delete the show
      parameters:
        - in: path
          name: eshowid
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: Show not found
        '500':
          description: Intenal Server Error
          
  /api/updateshow/{showid}:
    put:
      tags:
        - show
      summary: Update the show
      description: Update the show
      parameters:
        - in: path
          name: showid
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: show_name
                content:
                  type: string
                  example: show_content
                list_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Show updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: showname
                  content:
                    type: string
                    example: show_content
                  list_id:
                    type: integer
                    example: 1
                  
        '404':
          description: Show Name not exists
        '500':
          description: Internal Server Error